### ISSUE TITLE
LaunchBar Error

### ISSUE THREAD

**Issue by umerez** [hlissner/lb6-actions#6] opened 2015-01-24 17:58 UTC
Hello,

This is the error I receive. 
![screenshot of safari 2015-01-24 18 51 16](https://cloud.githubusercontent.com/assets/10687026/5888323/c9186a66-a3fa-11e4-9b34-98ff5a0a9369.png)

I'm not savvy at all, sorry. I see no new Bitlink in my Bitly account, so I'm guessing nothing is being sent there.

Thanks in advance. Regards,

Esteban

**Comment by hlissner** [comment] 2015-01-25 02:29
Odd. Are you certain your typed your access token correctly? Hold down control when you run the action and it will prompt for the access token again.

If you don't have one, you can generate a token at https://bitly.com/a/oauth_apps

**Comment by umerez** [comment] 2015-01-25 08:33
Yes, I copy and pasted my API key, I checked again and the key is OK. But the error  still occurs. I don't see any significant message in the Console.

**Comment by hlissner** [comment] 2015-01-25 08:38
What URL are your trying to shorten? I'll try to reproduce the issue on my end.

**Comment by umerez** [comment] 2015-01-25 08:39
I've tried with a few different URLs, here's one: http://www.elcorreo.com/bizkaia/sociedad/201501/24/diez-cafes-asombrosos-londres-20150113094714.html

**Comment by hlissner** [comment] 2015-01-25 08:43
Very strange. It is working fine on my end. Are you using the latest version of LaunchBar?

**Comment by umerez** [comment] 2015-01-25 08:53
I think so: Version 6.1.6 (6113).

I don't know what the problem can be, and I really don't know how to help to narrow it down. All I can think of is that I'm not using an administrator account in my Mac, but a standard account. But I guess that has nothing to do with it.

**Comment by hlissner** [comment] 2015-01-25 09:32
I've figured out the problem. It has to do with Bit.ly's response.

Please try this updated version of the action: https://dl.dropboxusercontent.com/u/2908279/Shorten%20URL%20%28Bit.ly%29.lbaction.zip

If it still doesn't work, it will print out BIt.ly's response into the console.

Let me know!

**Comment by umerez** [comment] 2015-01-25 09:48
Thanks a lot. I'm so sorry, a new error occurred: This url could not be shortened: undefined.

There is a response in the console, though: 

2015-01-25 10:43:48,701 LaunchBar[38588]: Shorten URL (Bit.ly) (io.henrik.launchbar.ShortenURLBitly): {"status_txt":"INVALID_ARG_ACCESS_TOKEN","data":[],"status_code":500}

I held the control key while launching the action and entered my API key. The console showed the same message.

**Comment by hlissner** [comment] 2015-01-25 10:12
It's no trouble at all! Although, judging from Bit.ly's response, your access token *is* invalid. Maybe you copied more than just the API key when you copy-pasted it?

I've updated the action to give better error messages depending on bit.ly's responses.

**Comment by umerez** [comment] 2015-01-25 11:23
So I reset my API key in Bitly, made sure I was copy-pasting it correctly, and the same error occurred. Now, due to your update, the message is "Your API key is invalid". I don't want to bother you anymore, since I really don't know what to do. Thank you very much.

**Comment by hlissner** [comment] 2015-01-28 16:55
You're very welcome. A shame we couldn't figure it out. 

I'll close this issue since it doesn't appear to be caused by the action. Take care!

**Closed by hlissner** 2015-01-28 16:55 UTC
